solutions/eliseworthy/config/routes.rb
StoreEngine::Application.routes.draw do
  resources :category_assignments

  resources :categories

  match "/about" => "pages#about", :as => :about
  match "/code" => redirect("https://github.com/eliseworthy/store_engine"), :as => :code
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  post "orders/one-click/:product_id" => "orders#one_click", :as => "one_click"

  resources :users
  resources :sessions
  resources :line_items
  resources :order_items
  resources :carts
  root to: "products#index"
  resources :products
  resources :orders do
    collection do
      get "admin_report"
    end
  end
end
  

solutions/eliseworthy/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href='http://fonts.googleapis.com/css?family=Average' rel='stylesheet' type='text/css'>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>StoreEngine</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </a> 

          <div class="brand">
            <img src="/assets/logo.png" /> 
            <p>
              <%= link_to "WholeEarth Products", root_path %>
              Certified Sustainable 
            </p>
          </div>
        
          <div class="nav-collapse">
            <p class="nav">  
              <% if current_user %>
                <%= current_user.email %>
              <% end %>
            </p>  
            
            <ul class="nav">
              <li><%= link_to "Why WholeEarth?", about_path %></li>
              <li>
                <%= link_to "View Cart", cart_path(current_cart)  %>
              </li> 

            <% if current_user %>
              <li>
                <%= link_to "View My Orders", orders_path %>
              </li>
              <li>
                <%= link_to "Log Out", logout_path %>
              </li>  
            <% else %>
              <li>
                <%= link_to "Sign Up", signup_path %>
              </li>
              <li>
                <%= link_to "Log in", login_path %>
              </li>  
            <% end %>
              <li><%= link_to "View the Code", code_path %></li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <div class="container">

      <div class="content topper">
        <div class="row">
           <div class="span8">
              <% flash.each do |name, message| %>
                <div class="alert alert-<%= name == :notice ? "success" : "error"%>">
                <a class="close" data-dismiss="alert">x</a>
                <%= notice %>
                </div>
              <% end %>

              <%= yield %>
            </div>

            <div class="span4">
              <div class="well sidebar-nav">
                <h3><%= link_to "View all Products", products_path %></h3>
                <h3>Shop All Products by Category</h3>
                <ul class="nav nav-list">
                  
                  <% Category.all.each do |category|%>
                    <li> 
                      <%= link_to category.name, category_path(category) %>
                    </li>
                  <% end %>   
                </ul>
              </div><!--/.well -->
              <% if can? :create, @product %>
                <div class="well sidebar-nav">
                  <div class = "admin_nav">
                    <h3>Admin Actions</h3>
                    <ul class="nav nav-list">
                      <li><%= link_to 'Create New Product', new_product_path %></li>
                      <li><%= link_to 'Create New Category', new_category_path %></li>
                      <li><%= link_to 'View All Categories', categories_path %></li>
                      <li><%= link_to 'View All users', users_path%></li>
                      <li><%= link_to "View Admin Order Report", admin_report_orders_path%></li>
                    </ul>
                  </div> 
                </div><!--/.well -->
              <% end %>
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; WholeEarth Products 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>