config/routes.rb
StoreEngine::Application.routes.draw do
  root to: 'products#index'

  get "/logout" => "sessions#destroy", :as => "logout"
  get "/login" => "sessions#new", :as => "login"
  get "/signup" => "users#new", :as => "signup"

  get "/account" => redirect("/account/profile")
  get "/account/profile" => "users#show"
  get "/account/orders" => "orders#index"
  get "/account/ratings" => "ratings#index"
  get "/account/orders/:id" => "orders#show", :as => "account_order"
  post "/buy_now" => "orders#buy_now", :as => 'buy_now'
  put "/i18n" => "i18n#update"

  resources :sessions, only: [ :new, :create, :destroy ]
  resources :products, only: [ :index, :show ] do
    resources :ratings
  end

  resource :cart, only: [ :update, :show, :destroy ] do
    member do
      put :remove_item
    end
  end

  resources :users, only: [ :new, :create, :update ] do
    resources :orders
  end

  namespace :admin do
    root to: redirect("/admin/dashboard")
    get :dashboard, to: "orders#index", as: 'dashboard'
    get :search, to: "orders#index", as: 'search'
    resources :sales, as: 'sales' do
      member do
        post :end
        post :activate
      end
    end
    resources :orders, only: [ :show, :update ]
    resources :order_items, only: [ :update, :destroy]

    resources :products do
      member do
        post :retire
        post :activate
      end
    end

    resources :categories, except: [ :show ]
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :status, :user_id
  belongs_to :user
  has_many :order_items, dependent: :destroy
  has_many :products, through: :order_items

  validates :user_id, presence: true

  validates :status, presence: true,
                     inclusion: { in: %w(pending cancelled paid shipped returned),
                                  message: "%{value} is not a valid status" }

  def self.create_and_charge(params)
    order = create(status: 'pending', user_id: params[:user].id)

    params[:cart].items.each do |cart_item|
      order.order_items.create(product_id: cart_item.product.id,
                               unit_price: cart_item.unit_price,
                               selling_price: cart_item.selling_price,
                               percent_off: cart_item.percent_off,
                               quantity: cart_item.quantity)
    end

    payment = Payment.new_with_charge(token: params[:token],
                                      price: order.total,
                                      email: params[:user].email,
                                      order: order)
    order
  end

  def update_status
    next_status = { 'pending' => 'cancelled',
                    'paid' => 'shipped',
                    'shipped' => 'returned' }
    self.status = next_status[self.status]
    self.save
  end

  def total
    if order_items.present?
      order_items.map {|order_item| order_item.subtotal }.inject(&:+)
    else
      0
    end
  end

  def value
    total + total_discount
  end

  def total_discount
    if order_items.present?
      order_items.map {|order_item| order_item.total_discount }.inject(&:+)
    else
      0
    end
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_filter :require_admin

  def index
    @count = Order.count
    @orders = Search.filter_admin_orders(params)
    @statuses = Order.count(group: :status)
    @active_tab = params[:status] || 'all'
    #@dashboard = OrderDashboard.new(params[:status])
    #@dashboard.statuses # => [ [ 16, "total", "all" ], []

  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if params[:update_status]
      @order.update_status
    end
    redirect_to(:back)
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController

  before_filter :lookup_order, :only => [:show, :edit, :destroy, :update]
  
  def index
    @orders = order.all
  end

  def show
  end

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  def new
    @order = order.new
  end

  def create
    @order = order.new(params[:order])
    if @order.save
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @order.update_attributes(params[:order])
    @order.save
    redirect_to order_path(@order)
  end

  def lookup_order
    @order = order.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :require_login

  def new
    @order = Order.new
  end

  def index
    @orders = Search.filter_user_orders(current_user.id, params)
  end

  def show
    order = Order.find(params[:id])
    if current_user.id == order.user_id
      @order = Order.find(params[:id])
    else
      redirect_to account_orders_path
    end
  end

  def create
    @order = Order.create_and_charge(cart: current_cart,
                                     user: current_user,
                                     token: params[:stripeToken])
    if @order.valid?
      session[:cart] = current_cart.destroy
      redirect_to user_order_path(current_user, @order), :notice => "Successfully created order!"
    else
      redirect_to cart_path, :notice => "Checkout failed."
    end
  end

  def buy_now
    @order = Order.create_and_charge(cart: Cart.new({params[:order] => '1'}),
                                     user: current_user,
                                     token: params[:stripeToken])
    if @order.valid?
      session[:cart] = current_cart.destroy
      redirect_to user_order_path(current_user, @order), :notice => "Successfully created order!"
    else
      redirect_to cart_path, :notice => "Checkout failed."
    end
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
  def next_status(current_status)
    { 'pending' => t('order.status.next.pending'),
      'paid' => t('order.status.next.paid'),
      'shipped' => t('order.status.next.shipped')}[current_status]
  end

  def status_count(status)
    count = @statuses[status] || 0
    "#{count} #{t('order.status.' + status)}"
  end
end

app/views/admin/orders/_admin_dashboard_nav.html.erb
<ul class="nav nav-pills">
<% if active_tab == 'all' %>
<li class="active">
<% else %>
<li>
<% end %>
<%= link_to "#{count} #{t 'total'}", admin_dashboard_path %>
</li>
<% %w(pending cancelled paid shipped returned).each do |status| %>
  <% if active_tab == status %>
  <li class="active">
  <% else %>
  <li>
  <% end %>
  <%= link_to status_count(status), admin_dashboard_path(status: status) %>
  </li>
<% end %>
</ul>

app/views/admin/orders/_advanced_search_form.html.erb
<form class="form-horizontal">
  <div class="control-group">
    <label class="control-label">Status</label>
    <div class="controls">
      <select id="admin-order-search-status" name="status" class="input-small">
        <option <%= 'selected' if params[:status] == 'all' %>>all</option>
        <option <%= 'selected' if params[:status] == 'pending' %>>pending</option>
        <option <%= 'selected' if params[:status] == 'paid' %>>paid</option>
        <option <%= 'selected' if params[:status] == 'shipped' %>>shipped</option>
        <option <%= 'selected' if params[:status] == 'cancelled' %>>cancelled</option>
        <option <%= 'selected' if params[:status] == 'returned' %>>returned</option>
      </select>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Price</label>
    <div class="controls">
      <select id='admin-order-search-price-symbol' name="price_symbol" class="input-mini">
        <option <%= 'selected' if params[:price_symbol] == '>' %>>></option>
        <option <%= 'selected' if params[:price_symbol] == '<' %>><</option>
        <option <%= 'selected' if params[:price_symbol] == '=' %>>=</option>
      </select>
      <div class="input-append">
        <input class="span1" id="admin-order-search-price" name="price" value="<%= params[:price] %>" type="text" placeholder="10000">
        <span class="add-on">¢</span>
      </div>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Date</label>
    <div class="controls">
      <select id='admin-order-search-date-symbol' name="date_symbol" class="input-mini">
        <option <%= 'selected' if params[:date_symbol] == '>' %>>></option>
        <option <%= 'selected' if params[:date_symbol] == '<' %>><</option>
        <option <%= 'selected' if params[:date_symbol] == '=' %>>=</option>
      </select>
      <input type="date" name="date" value="<%= params[:date] %>" class="span2" id="admin-order-search-date">
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">Purchaser Email</label>
    <div class="controls">
      <input type="text" value="<%= params[:email] %>"class="input-medium" id="admin-order-search-email" name="email">
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <input type="hidden" name="admin" value="true">
      <button type="submit" class="btn btn-primary">Search Orders</button>
    </div>
  </div>
</form>

<h3>Results</h3>
<hr>

app/views/admin/orders/_next_status_button.html.erb
<% if next_status(order.status) %>
<%= button_to next_status(order.status),
              admin_order_path(order, update_status: true),
              method: :put, class: 'btn btn-mini' %>
<% end %>

app/views/admin/orders/_order.html.erb
<tr>
  <td><%= link_to "#{t('order.self')} ##{order.id}", admin_order_path(order) %></td>
  <td><%= order.created_at.to_s(:short) %></td>
  <td><%= order.status %></td>
  <td>
    <%= render partial: 'next_status_button', locals: { order: order } %>
  </td>
</tr>

app/views/admin/orders/_order_item.html.erb
<tr>
  <td><%= link_to order_item.product.title, product_path(order_item.product) %></td>
  <% if @order.status == ('pending' || 'paid') %>
  <td>
    <%= simple_form_for :admin_order_item, url: "/admin/order_items/#{order_item.id}", method: :put do |f| %>
      <%= f.hidden_field :order_item_id, value: order_item.id %>
      <%= f.input_field :quantity, value: order_item.quantity, class: 'span1' %>
      <%= f.button :submit, t('crud.update'), class: 'btn-mini' %>
    <% end %>
    <%= button_to t('crud.delete'), admin_order_item_path(order_item), method: :delete, class: 'btn btn-mini btn-danger' %>
  </td>
  <% else %>
  <td><%= order_item.quantity %></td>
  <% end %>
  <td><%= number_to_currency(order_item.unit_price) %></td>
  <td><%= number_to_currency(order_item.subtotal) %></td>
</tr>

app/views/admin/orders/index.html.erb
<div class="admin-order-index">
  <%= render partial: 'shared/admin_navigation',
             locals: { active: current_page?(admin_dashboard_path) ? :dashboard : :search } %>

  <div class="span8">
    <h1><% if current_page?(admin_dashboard_path) %><%= t 'admin.dashboard' %><% else %>Search<%end%></h1>
    <hr>

    <% if @count > 0 %>

        <% if current_page?(admin_search_path) %>
            <%= render 'advanced_search_form' %>
        <% else %>
            <%= render partial: 'admin_dashboard_nav', locals: {active_tab: @active_tab,
                                                                count: @count,
                                                                statuses: @statuses} %>
        <% end %>
        <br>
        <table class="table">
          <thead>
          <th>#</th>
          <th><%= t 'model.createdat' %></th>
          <th><%= t 'model.status' %></th>
          <th><%= t 'model.modify' %></th>
          </thead>
          <tbody>
          <%= render @orders %>
          </tbody>
        </table>
    <% else %>
        <%= t 'order.none' %>
    <% end %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="admin-order-show">
  <%= render partial: 'shared/admin_navigation', locals: { active: false } %>

  <div class="span8">
    <h1><%= t 'order.self' %> #<%= @order.id %></h1>
    <p><%= t 'model.status' %> <%= @order.status %></p>
    <%= render partial: 'next_status_button', locals: { order: @order } %>
    <hr>
    <p><%= t 'model.createdat' %>: <%= @order.created_at.to_s(:short) %></p>
    <p><%= t 'model.updatedat' %>: <%= @order.updated_at.to_s(:short) %></p>
    <p><%= t 'order.purchasername' %>: <%= @order.user.full_name %></p>
    <p><%= t 'order.purchaseremail' %>: <%= @order.user.email %></p>
    <h2> <%= t 'product.collection' %> </h2>
    <table class="table">
      <thead>
      <th><%= t 'product.title' %></th>
      <th><%= t 'product.quantity' %></th>
      <th><%= t 'product.price' %></th>
      <th><%= t 'product.subtotal' %></th>
      </thead>
      <tbody>
      <%= render partial: 'order_item', collection: @order.order_items %>
      </tbody>
      <tfoot>
      <tr>
        <td></td>
        <td></td>
        <td style="text-align: right;"><%= t 'total' %></td>
        <td><%= number_to_currency(@order.total) %></td>
      </tr>
      </tfoot>
    </table>
  </div>
</div>