solutions/athal7/config/routes.rb
StoreEngine::Application.routes.draw do

  get 'sessions/new', :as => 'login_page'
  get 'sessions/index'
  post 'sessions/create', :as => 'login'
  delete 'sessions/destroy', :as => 'logout'

  match '/code' => redirect('http://github.com/athal7/store_engine')

  resources :users, except: :destroy do
    member do
      put :view_as_admin
      put :view_as_normal
    end
  end

  resources :products do
    member  do
      put :retire
    end
  end

  resources :categories
  resources :orders, except: [:new, :create]
  resources :billing_methods, except: [:destroy]
  resources :line_items, except: [:new]
  resources :shipping_addresses, except: [:destroy]
  root to: "products#index"

end

solutions/athal7/app/models/order.rb
#
class Order < ActiveRecord::Base
  attr_accessible :billing_method_id, :user_id, :status, :shipping_address_id

  validates_presence_of :status

  belongs_to :billing_method
  belongs_to :user
  belongs_to :shipping_address
  has_many :line_items
  has_many :products, through: :line_items

  def date
    created_at.strftime("%B %d at %l:%M %p")
  end

  def pending?
    status == "pending"
  end

  def user
    return nil if self.user_id == nil
    User.find(self.user_id)
  end

  def amount
    line_items.map(&:subtotal).inject(:+)
  end

  def transition
    if status == "pending"
      if billing_method_id && shipping_address_id
        update_attribute(:status, next_transition)
      else
        false
      end
    else
      set_action_time(next_transition)
      update_attribute(:status, next_transition)
    end
  end

  def next_transition
    if status == "pending"
      "paid"
    elsif status == "paid"
      "shipped"
    elsif status == "shipped"
      "returned"
    end
  end

  def set_action_time(transition)
    if transition == "shipped" || transition == "cancelled"
      update_attribute(:action_time, Time.now)
    end
  end

  def user_name
    return "Guest" if user.nil?
    user.display_name
  end

  def user_email_address
    user.email_address
  end

  def guest_email_address
    if shipping_address_id
      find_shipping.email_address
    else
      "no email yet"
    end
  end

  def has_product?(product_id)
    products.include? Product.find(product_id.to_i)
  end

  def has_billing_method?
    billing_method_id ? true : false
  end

  def find_billing
    BillingMethod.find(billing_method_id)
  end

  def credit_card_last_four
    find_billing.credit_card_number.last(4)
  end

  def has_shipping_address?
    shipping_address_id ? true : false
  end

  def find_shipping
    ShippingAddress.find(shipping_address_id)
  end

  def shipping_street
    find_shipping.street
  end

  def add_user(user_id)
    update_attribute(:user_id, user_id)
  end

  def try_to_add_billing_and_shipping(user_id)
    if user.has_billing_method?
      update_attribute(:billing_method_id, user.billing_method_id)
    end
    if user.has_shipping_address?
      update_attribute(:shipping_address_id, user.shipping_address_id)
    end
  end

  def total_items
    line_items.sum(&:quantity)
  end

end

solutions/athal7/app/controllers/orders_controller.rb
#
class OrdersController < ApplicationController
  before_filter :lookup_order, :only => [:show, :edit, :destroy, :update]
  before_filter :current_user, only: [:show]
  before_filter :require_order_user_or_admin, only: [:show]
  before_filter :require_admin, :only => [:destroy]

  def index
    if params[:status] == "all"
      @orders = Order.all
    elsif params[:status]
      @orders = Order.where(:status => params[:status])
    else
      @orders = Order.all
    end
  end

  def show
  end

  def destroy
    session[:return_to] = request.url
    cancel_order
    notice = "Order Cancelled"
    redirect_to session[:return_to], notice: notice
  end

  def edit
  end

  def update
    if @order.status == "pending" && @order.transition
      check_out
    elsif @order.status != "pending" && @order.transition
      transition_status
    else
      notice = "Please input valid billing and shipping information."
      redirect_to order_path(@order), notice: notice
    end
  end

  private

  def lookup_order
    @order = Order.find(params[:id])
  end

  def cancel_order
    @order.update_attribute(:status, "cancelled")
    @order.set_action_time("cancelled")
    session[:order_id] = nil if @order.user == current_user
  end

  def check_out
    link = "<a href=\"#{url_for(@order)}\">View Details</a>"
    notice = "Thank you for purchasing. #{link}".html_safe
    session[:previous_order_id] = session[:order_id] if !logged_in?
    session[:order_id] = nil
    redirect_to root_url, notice: notice
  end

  def transition_status
    session[:return_to] = request.url
    notice = "Transition successful"
    redirect_to session[:return_to], notice: notice
  end

end

solutions/athal7/app/helpers/orders_helper.rb
module OrdersHelper
  def current_order
    return Order.find(session[:order_id]) if session[:order_id]
  end
  def require_order_user_or_admin
    if !logged_in? && not_guests_order?
      redirect_to root_url, notice: "Sorry, you are not allowed to view that."
    elsif order_does_not_belong_to_user && !admin_view?
      redirect_to root_url, notice: "Sorry, you are not allowed to view that."
    end
  end
end


private

def order_does_not_belong_to_user
  current_order.nil? && @order.user != current_user
end

def not_guests_order?
  @order.id != session[:order_id] && @order.id != session[:previous_order_id]
end

solutions/athal7/app/views/orders/_admin_buttons.html.slim
/! MAKE DIFFERENT TRANSITIONS FOR DIFFERENT ORDER STATUSES
- unless order.status == "returned" || order.status == "cancelled"
  = link_to "Mark as '#{order.next_transition}'", order_path(order), :method => :put, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-info'

= link_to 'Edit', edit_order_path(order), :class => 'btn btn-mini'

- if order.status == "pending"
  = link_to 'Cancel', order_path(order), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger'

solutions/athal7/app/views/orders/_billing.html.slim
- if order.has_billing_method?
  - billing = order.find_billing
  h2 Billing Method
  | Credit Card ending in: #{order.credit_card_last_four}
  br/
  - if order.pending?
    = link_to "Change Billing Method", edit_billing_method_path(billing), class: "btn-mini btn"
- elsif order == current_order
  = link_to "Add a Billing Method", new_billing_method_path, class: "btn-mini btn"

solutions/athal7/app/views/orders/_filter.html.slim
h3 Filter Order By Status
= form_tag orders_path, method: :get do
  = select_tag :status, options_for_select([["all", "all"], ["pending", "pending"], ["cancelled", "cancelled"], ["paid", "paid"], ["shipped", "shipped"], ["returned", "returned"]]), :prompt => "Status", class: 'text_field'
  = submit_tag "Update"

solutions/athal7/app/views/orders/_form.html.slim
= form_for @order do |f|
  .control-group
    = f.label :status, :class => 'control-label'
    .controls
      = f.text_field :status, :class => 'text_field'

  .form-actions
    = f.submit :class => 'btn btn-primary'
    = link_to 'Cancel', orders_path, :class => 'btn'

solutions/athal7/app/views/orders/_line_item.html.slim
tr
  td = link_to line_item.product.title, product_path(line_item.product)
  td
    = line_item.quantity
    - if line_item.order.status == "pending"
      = link_to "Update", edit_line_item_path(line_item), class: 'btn'
  td = number_to_currency(line_item.price)
  td = number_to_currency(line_item.subtotal)
  - if order.pending?
    td = link_to "Remove", line_item_path(line_item),
     method: :delete, class: 'btn btn-mini btn-danger'

solutions/athal7/app/views/orders/_order.html.slim
- if order.user_id == current_user.id || admin_view?
  tr
    - if admin_view?
      td = render partial: "admin_buttons", locals: { order: order }
      - if order.user.nil?
        td Guest
        td = order.guest_email_address
      - else
        td = link_to order.user_name, user_path(order.user)
        td = link_to order.user_email_address, user_path(order.user)
    td = link_to order.id, order_path(order)
    td = order.date
    td = render partial: "order_item", collection: order.line_items
    td = number_to_currency(order.amount)
    td
      = order.status
      - if order.status == "cancelled" || order.status == "shipped"
        br/
        =order.action_time

solutions/athal7/app/views/orders/_order_head.html.slim
#date= order.created_at

#date= order.status
- unless order.status == "returned" || order.status == "cancelled"
  = link_to "Mark as '#{order.next_transition}'", order_path(order), :method => :put, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-info'

solutions/athal7/app/views/orders/_order_header.html.slim
- if order.status == "pending"
  h1 Cart
  - if admin_view?
    = render partial: "order_head", locals: { order: order }
- else
  h1 Order
  #order-status
    = order.status.upcase
  - if admin_view?
    = render partial: "order_head", locals: { order: order }

solutions/athal7/app/views/orders/_order_item.html.slim
= order_item.quantity
| x
= link_to order_item.title, product_path(order_item.product)
br/

solutions/athal7/app/views/orders/_shipping.html.slim
- if order.has_shipping_address?
  - shipping = order.find_shipping
  h2 Shipping Address
  | Street: #{order.shipping_street}
  br/
  - if order.pending?
    = link_to "Change Shipping Address", edit_shipping_address_path(shipping), class: "btn-mini btn"
- elsif order == current_order
  br/
  = link_to "Add a Shipping Address", new_shipping_address_path, class: "btn-mini btn"

solutions/athal7/app/views/orders/edit.html.slim
= render partial: "form"

solutions/athal7/app/views/orders/index.html.slim
h1 Orders
= render partial: "filter"
- if @orders.count > 0
  table.table.table-striped#order-table
    thead
      tr
        - if admin_view?
          th Actions
          th Purchaser
          th Email
        th Order Id
        th Order Date
        th Items
        th Subtotal
        th Status
    tbody
      = render partial: "order", collection: @orders
- else
 h3 = "No Orders Match Your Criteria"

solutions/athal7/app/views/orders/new.html.slim
h1 Nothing in your cart yet
= link_to "Shop", root_url, class: "btn btn-success"

solutions/athal7/app/views/orders/show.html.slim
- if @order.line_items.present?
  = render partial: "order_header", locals: {order: @order}
  table.table.table-striped
    tr
      th Product Name
      th Product Quantity
      th Unit Price
      th Subtotal
      - if @order.pending?
        th Actions
      = render partial: "line_item", collection: @order.line_items, locals:{order: @order}

  = render partial: "billing", locals: {order: @order}
  = render partial: "shipping", locals: {order: @order}

  h2#subtotal Total: #{ number_to_currency(@order.amount)}
  br/
  - if @order.pending?
    = link_to "Check Out", order_path(@order), method: :put, class: "btn btn-success"
-else
  h3 #{"Your Cart is Empty"}
  = link_to "Browse Products", root_path, class: "btn btn-success"